[package]
name = "didjs"
version = "0.1.0"
edition = "2018"

[lib]
path = "lib.rs"
crate-type = ["cdylib"]

[dependencies]
ic0 = "0.21.1"
candid = "0.9"
ic-cdk = "0.11"
ic-cdk-macros = "0.8.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_bytes = "0.11.12"
